export const ActionTypes = {
  SET_ARGS: "SET_ARGS",
  SET_EXPECTED_OUTPUT: "SET_EXPECTED_OUTPUT",
  SET_GUESS: "SET_GUESS",
  ADD_ARGUMENT: "ADD_ARGUMENT",
  REMOVE_ARGUMENT: "REMOVE_ARGUMENT",
  CONFIRM_JSON_ALERT: "CONFIRM_JSON_ALERT"
};
